services:
  mc-anvil-db:
    build: .
    container_name: mc-anvil-db
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    env_file: .env
    environment:
      - RUST_LOG=info
    volumes:
      - type: bind
        source: ./fuse_region
        target: /mnt/region
        bind:
          propagation: rshared
    healthcheck:
      test: ["CMD", "mountpoint", "-q", "/mnt/region"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgis/postgis:18-3.6-alpine
    container_name: postgres
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  minecraft:
    image: itzg/minecraft-server:java21-alpine
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.11
    volumes:
      - minecraft_data:/data
      - type: bind
        source: ./fuse_region
        target: /data/world/region
        bind:
          propagation: rslave
    depends_on:
      mc-anvil-db:
        condition: service_healthy

volumes:
  db_data:
  minecraft_data:
