[package]
name = "hoppermc-storage"
version = "0.0.5"
edition = "2024"

[dependencies]
tokio-postgres = { workspace = true }
deadpool-postgres = { workspace = true }
postgis = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
